# Generated by Django 4.2.13 on 2024-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nk_api', '0002_alter_api_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='region',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Region', max_length=100, null=True),
        ),
    ]
